version: "3.8"

services:
  db:
    container_name: clinic
    image: postgres:latest
    environment:
      POSTGRES_USER: MohamedFrh
      POSTGRES_PASSWORD: khouyafiras28
      POSTGRES_DB: clinic
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5232:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
